# Generated by Django 4.2.11 on 2024-04-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='group_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupmember'),
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category'),
        ),
        migrations.AddField(
            model_name='board',
            name='group_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupmember'),
        ),
    ]
