# Generated by Django 4.2.11 on 2024-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='modified_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='modified_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
